sudo: required
services:
    - docker

before_install:
    - docker build -t benedery/docker-react -f Dockerfile.travis .

#script contain all commands to run test suits
script:
    - docker run -e CI=true benedery/docker-react yarn run test